# canary test version 2 of app along side version 1
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: election-v2-canary
  namespace: test
spec:
  destination:
    name: election
  route:
  - labels:
      app: election
      version: v2
    weight: 50
  - labels:
      app: election
      version: v1
    weight: 50
