# kubectl apply -f ./routerules/routerule-election-v1.yaml -n dev
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: election-v1
spec:
  destination:
    name: election
  match:
    request:
      headers:
        uri:
          prefix: /v1/
  rewrite:
    uri: /
  route:
  - labels:
      app: election
      version: v1
