#server:
#  port: 0
spring:
  application:
    name: PCF Spring PostgreSQL Demo v2.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/elections
    username: postgres
    password: postgres1234
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
message: The 'default' Profile is active
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG
---
spring:
  profiles: dev
message: The 'dev' Profile is active
---
spring:
  profiles: test
message: The 'test' Profile is active
logging:
  level:
    root: INFO
---
spring:
  profiles: uat
  jpa:
    show-sql: false
message: The 'uat' Profile is active
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
logging:
  level:
    root: WARN
---
spring:
  profiles: prod
  jpa:
    show-sql: false
message: The 'prod' Profile is active
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
logging:
  level:
    root: WARN
