apiVersion: v1
kind: Secret
metadata:
  name: postgresql-conn-info
  labels:
    name: test
    type: db
  namespace: test
type: Opaque
data:
  url: <your_conn_info>
  username: <your_conn_info>
  password: <your_conn_info>
