apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: springapp-v1
spec:
  replicas: 2
  strategy: {}
  selector:
    matchLabels:
      app: springapp
      version: v1
  template:
    metadata:
      labels:
        app: springapp
        version: v1
    spec:
      containers:
      - name: springapp-v1
        image: garystafford/spring-postgresql-demo:1.0.0
        env:
        - name: SPRING_PROFILE
          value: dev
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE
          value: 5
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-connection-info
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-connection-info
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-connection-info
              key: password
        ports:
        - containerPort: 8080
      restartPolicy: Always
