apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  labels:
    name: test-ingress
  namespace: test
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /test/.*
        backend:
          serviceName: election
          servicePort: 8080
