# canary uat version 2 of app along side version 1
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: election-v2-canary
  namespace: uat
spec:
  destination:
    name: election
  match:
    request:
      headers:
        uri:
          prefix: /uat/
  rewrite:
    uri: /
  route:
  - labels:
      app: election
      version: v2
    weight: 100
  - labels:
      app: election
      version: v1
    weight: 0
