apiVersion: v1
kind: Service
metadata:
  labels:
    istio-injection: enabled
    app: postgres
  name: postgres
spec:
  ports:
  - name: tcp
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
status: {}
